fix: Add missing typenames ('Playable' and 'T')
/app/Includes/Rosetta/Zones/Zone.hpp:211:11: error: class 'RosettaStone::LimitedZone<T>' does not have any field named 'Zone'
         : Zone(type), m_maxSize(maxSize)
           ^~~~